src/Entity/Meeting.php
<?php

namespace App\Entity;

use App\Repository\MeetingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MeetingRepository::class)
 */
class Meeting
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meeting_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meeting_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mod_pass;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_pass;

    /**
     * @ORM\ManyToOne(targetEntity=Orgaunit::class, inversedBy="meetings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $host;

    /**
     * @ORM\OneToMany(targetEntity=JoinToken::class, mappedBy="meeting")
     */
    private $joinTokens;

    /**
     * @ORM\Column(type="boolean")
     */
    private $currentlyActive;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function __construct()
    {
        $this->joinTokens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMeetingId(): ?string
    {
        return $this->meeting_id;
    }

    public function setMeetingId(string $meeting_id): self
    {
        $this->meeting_id = $meeting_id;

        return $this;
    }

    public function getMeetingName(): ?string
    {
        return $this->meeting_name;
    }

    public function setMeetingName(string $meeting_name): self
    {
        $this->meeting_name = $meeting_name;

        return $this;
    }

    public function getModPass(): ?string
    {
        return $this->mod_pass;
    }

    public function setModPass(string $mod_pass): self
    {
        $this->mod_pass = $mod_pass;

        return $this;
    }

    public function getUserPass(): ?string
    {
        return $this->user_pass;
    }

    public function setUserPass(string $user_pass): self
    {
        $this->user_pass = $user_pass;

        return $this;
    }

    public function getHost(): ?Orgaunit
    {
        return $this->host;
    }

    public function setHost(?Orgaunit $host): self
    {
        $this->host = $host;

        return $this;
    }

    /**
     * @return Collection|JoinToken[]
     */
    public function getJoinTokens(): Collection
    {
        return $this->joinTokens;
    }

    public function addJoinToken(JoinToken $joinToken): self
    {
        if (!$this->joinTokens->contains($joinToken)) {
            $this->joinTokens[] = $joinToken;
            $joinToken->setMeeting($this);
        }

        return $this;
    }

    public function removeJoinToken(JoinToken $joinToken): self
    {
        if ($this->joinTokens->removeElement($joinToken)) {
            // set the owning side to null (unless already changed)
            if ($joinToken->getMeeting() === $this) {
                $joinToken->setMeeting(null);
            }
        }

        return $this;
    }

    public function getCurrentlyActive(): ?bool
    {
        return $this->currentlyActive;
    }

    public function setCurrentlyActive(bool $currentlyActive): self
    {
        $this->currentlyActive = $currentlyActive;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/MeetingController.php
<?php


namespace App\Controller;


use App\Entity\JoinToken;
use App\Entity\Meeting;
use BigBlueButton\BigBlueButton;
use BigBlueButton\Parameters\CreateMeetingParameters;
use BigBlueButton\Parameters\IsMeetingRunningParameters;
use BigBlueButton\Parameters\JoinMeetingParameters;
use Doctrine\ORM\Query\AST\Join;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\Mailer;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Ulid;
use Symfony\Component\Validator\Constraints\Uuid;

/**
 * @Route("/meetings")
 */
class MeetingController extends AbstractController
{
    /**
     * @Route("/")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    function list(){
        $meetings = $this->getDoctrine()->getRepository(Meeting::class)->findBy([
            "host" => $this->getUser()->getOrgaunit()
        ]);

        return $this->render('meetings/list.html.twig', [
            "meetings" => $meetings,
            "title" => "Meeting-Übersicht"
        ]);
    }

    /**
     * @Route("/delete/{id}")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    function delete($id){
        $meeting = $this->getDoctrine()->getRepository(Meeting::class)->find($id);
        if($this->getUser()->getOrgaUnit() == $meeting->getHost()){
            if($meeting){
                if(sizeof($meeting->getJoinTokens()) != 0){
                    $this->addFlash("error", "Ein Fehler ist aufgetreten!|Es bestehen noch JoinTokens. Bitte löschen Sie diese, bevor Sie das Meeting löschen!");
                    return $this->redirectToRoute('app_meeting_list');
                }
                $em = $this->getDoctrine()->getManager();
                $em->remove($meeting);
                $em->flush();
                return $this->redirectToRoute('app_meeting_list');
            }else{
                return $this->redirectToRoute('app_meeting_list');
            }
        }else{
            return $this->redirectToRoute('app_meeting_list');
        }
    }

    /**
     * @Route("/detail/{id}")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    function detail($id){
        $meeting = $this->getDoctrine()->getRepository(Meeting::class)->find($id);
        if($this->getUser()->getOrgaUnit() == $meeting->getHost()){
            if($meeting){
                return $this->render('meetings/info.html.twig', [
                    "meeting" => $meeting,
                    "title" => "Detail-Infos"
                ]);
            }else{
                return $this->redirectToRoute('app_meeting_list');
            }
        }else{
            return $this->redirectToRoute('app_meeting_list');
        }
    }

    /**
     * @Route("/start/{id}")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    function startMeeting($id){
        $meeting = $this->getDoctrine()->getRepository(Meeting::class)->find($id);
        if($this->getUser()->getOrgaUnit() == $meeting->getHost()){
            if($meeting){
                $bbb = new BigBlueButton();

                $createParams = new CreateMeetingParameters($meeting->getMeetingId(), $meeting->getMeetingName() . " | " . $meeting->getHost()->getName());
                $createParams->setModeratorPassword($meeting->getModPass());
                $createParams->setAttendeePassword($meeting->getUserPass());
                $createParams->setLogoutUrl($meeting->getHost()->getWebsite());
                $createParams->setEndCallbackUrl($this->generateUrl('app_api_meetingcallback_callbackurl', ['event' => "meetingEnded", "meetingId" => $meeting->getMeetingId()]));

                $bbb->createMeeting($createParams);

                $joinMeetingParams = new JoinMeetingParameters($meeting->getMeetingId(), $this->getUser()->getRealname(), $meeting->getModPass());
                $joinMeetingParams->setRedirect(true);

                $meeting->setCurrentlyActive(true);
                $this->getDoctrine()->getManager()->persist($meeting);
                $this->getDoctrine()->getManager()->flush();

                return $this->redirect($bbb->getJoinMeetingURL($joinMeetingParams));

            }else{
                return $this->render('meetings/notfound.html.twig');
            }
        }else{
            return $this->render('meetings/notfound.html.twig');
        }
    }

    /**
     * @Route("/join/{token}")
     */
    function joinMeetingAttendee($token){
        $jointoken = $this->getDoctrine()->getRepository(JoinToken::class)->findOneBy([
            "token" => $token
        ]);

        $bbb = new BigBlueButton();
        $meeting = $jointoken->getMeeting();
        $joinMeetingParams = new JoinMeetingParameters($meeting->getMeetingId(), $jointoken->getRealname(), $meeting->getUserPass());
        $joinMeetingParams->setRedirect(true);
        return $this->redirect($bbb->getJoinMeetingURL($joinMeetingParams));
    }

    /**
     * @Route("/create")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    function createMeeting(Request $request){
        $createmeeting = new Meeting();
        $form = $this->createForm('App\Form\CreateMeetingType', $createmeeting);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $createmeeting->setMeetingId(uniqid());
            $createmeeting->setModPass($this->getRandomString(20));
            $createmeeting->setUserPass($this->getRandomString(20));
            $createmeeting->setHost($this->getUser()->getOrgaunit());
            $createmeeting->setCurrentlyActive(false);

            $em = $this->getDoctrine()->getManager();
            $em->persist($createmeeting);
            $em->flush();
        }

        return $this->render('meetings/create.html.twig', [
            "form" => $form->createView(),
            "title" => "Meeting erstellen"
        ]);
    }

    /**
     * @Route("/detail/{meetingid}/tokens/create")
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     */
    function createJoinToken($meetingid, Request $request, MailerInterface $mailer){
        $meeting = $this->getDoctrine()->getRepository(Meeting::class)->find($meetingid);
        if($this->getUser()->getOrgaUnit() == $meeting->getHost()) {
            if ($meeting) {
                $createjointoken = new JoinToken();

                $form = $this->createForm('App\Form\CreateJoinTokenType', $createjointoken);
                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $createjointoken->setMeeting($meeting);
                    $createjointoken->setToken(uniqid());
                    $em = $this->getDoctrine()->getManager();
                    $em->persist($createjointoken);
                    $em->flush();

                    $tokenmail = (new TemplatedEmail())
                        ->from('LawMeet <lawmeet@it-media-hof.de>')
                        ->to($createjointoken->getEmail())
                        ->priority(Email::PRIORITY_HIGH)
                        ->subject('Sie wurden zu einer Besprechung eingeladen!')
                        ->htmlTemplate('mails/inviteEmail.html.twig')
                        ->context([
                            "jointoken" => $createjointoken,
                            "joinURL" => $this->generateUrl('app_meeting_joinmeetingattendee', ["token" => $createjointoken->getToken()], UrlGeneratorInterface::ABSOLUTE_URL)
                        ]);

                    $mailer->send($tokenmail);
                }

                return $this->render('meetings/jointokens/create.html.twig', [
                    "form" => $form->createView(),
                    "title" => "Jointoken erstellen"
                ]);
            } else {
                return $this->render('meetings/notfound.html.twig');
            }
        }else{
            return $this->redirectToRoute('app_meeting_list');
        }
    }

    /**
     * @Route("/detail/{meetingid}/tokens/{tokenid}/delete")
     */
    function deleteJoinToken($meetingid, $tokenid, MailerInterface $mailer){
        $meeting = $this->getDoctrine()->getRepository(Meeting::class)->find($meetingid);
        if($this->getUser()->getOrgaUnit() == $meeting->getHost()) {
            if($meeting){
                $token = $this->getDoctrine()->getRepository(JoinToken::class)->find($tokenid);

                $tokenmail = (new TemplatedEmail())
                    ->from('LawMeet <lawmeet@it-media-hof.de>')
                    ->to($token->getEmail())
                    ->priority(Email::PRIORITY_HIGH)
                    ->subject('Ein Besprechungslink wurde gelöscht!')
                    ->htmlTemplate('mails/deleteInviteEmail.html.twig')
                    ->context([
                        "jointoken" => $token
                    ]);

                $mailer->send($tokenmail);

                $em = $this->getDoctrine()->getManager();
                $em->remove($token);
                $em->flush();

                return $this->redirectToRoute('app_meeting_detail', ["id" => $meetingid]);
            }else{
                return $this->render('meetings/notfound.html.twig');
            }
        }else{
            return $this->redirectToRoute('app_meeting_list');
        }
    }



    function getRandomString($length = 8) {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $string = '';

        for ($i = 0; $i < $length; $i++) {
            $string .= $characters[mt_rand(0, strlen($characters) - 1)];
        }

        return $string;
    }

}

templates/meetings/create.html.twig
{% extends 'base-halfmoon.html.twig' %}

{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="content">
            <h1>Meeting erstellen</h1>
            <hr>
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_row(form.meeting_name, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">
                {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
            </div>
            <br>
            {{ form_row(form.submit, {'attr': {'class': 'btn btn-primary'}}) }}
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

templates/meetings/info.html.twig
{% extends 'base-halfmoon.html.twig' %}

{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="content">
            <h1>Meeting: {{ meeting.meetingName }}</h1>
            {% if(meeting.description is not null) %}
                <p>{{ meeting.description }}</p>
            {% endif %}

            <hr>
            <a href="{{ path('app_meeting_startmeeting', {id: meeting.id}) }}" class="btn btn-success">Meeting starten</a>
            <a href="{{ path('app_meeting_createjointoken', {meetingid: meeting.id}) }}" class="btn btn-primary">Jointoken erstellen</a>
            <hr>
            <table class="table">
                <thead>
                <tr>
                    <th>Teilnehmer</th>
                    <th>eMail-Adresse</th>
                    <th>Aktionen</th>
                </tr>
                </thead>
                <tbody>
                {% for jointoken in meeting.joinTokens %}
                <tr>
                    <th>{{ jointoken.realname }}</th>
                    <td>{{ jointoken.email }}</td>
                    <td>
                        <button class="btn btn-success" onclick="copyTextToClipboard('{{ url('app_meeting_joinmeetingattendee', {token: jointoken.token}) }}')">
                            <i class="fas fa-clipboard"></i>
                        </button>
                        <a href="{{ path('app_meeting_deletejointoken', {meetingid: meeting.id, tokenid: jointoken.id}) }}" class="btn btn-danger">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

    <script>
        function copyTextToClipboard(text) {
            var textArea = document.createElement("textarea");

            //
            // *** This styling is an extra step which is likely not required. ***
            //
            // Why is it here? To ensure:
            // 1. the element is able to have focus and selection.
            // 2. if the element was to flash render it has minimal visual impact.
            // 3. less flakyness with selection and copying which **might** occur if
            //    the textarea element is not visible.
            //
            // The likelihood is the element won't even render, not even a
            // flash, so some of these are just precautions. However in
            // Internet Explorer the element is visible whilst the popup
            // box asking the user for permission for the web page to
            // copy to the clipboard.
            //

            // Place in the top-left corner of screen regardless of scroll position.
            textArea.style.position = 'fixed';
            textArea.style.top = 0;
            textArea.style.left = 0;

            // Ensure it has a small width and height. Setting to 1px / 1em
            // doesn't work as this gives a negative w/h on some browsers.
            textArea.style.width = '2em';
            textArea.style.height = '2em';

            // We don't need padding, reducing the size if it does flash render.
            textArea.style.padding = 0;

            // Clean up any borders.
            textArea.style.border = 'none';
            textArea.style.outline = 'none';
            textArea.style.boxShadow = 'none';

            // Avoid flash of the white box if rendered for any reason.
            textArea.style.background = 'transparent';


            textArea.value = text;

            document.body.appendChild(textArea);
            textArea.focus();
            textArea.select();

            try {
                var successful = document.execCommand('copy');
                var msg = successful ? 'successful' : 'unsuccessful';
                console.log('Copying text command was ' + msg);
            } catch (err) {
                console.log('Oops, unable to copy');
            }

            document.body.removeChild(textArea);

            halfmoon.initStickyAlert({
                content: "Der Meetinglink wurde erfolgreich kopiert!",
                title: "Link kopiert",
                alertType: "alert-success",
                fillType: "filled-lm"
            });
        }
    </script>
{% endblock %}

templates/meetings/list.html.twig
{% extends 'base-halfmoon.html.twig' %}

{% block content %}
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="content">
            <h1>Meetings</h1>
            <hr>
            <table class="table">
                <thead>
                <tr>
                    <th>Meeting</th>
                    <th>Aktionen</th>
                </tr>
                </thead>
                <tbody>
                {% for meeting in meetings %}
                    <tr>
                        <th><a href="{{ path('app_meeting_detail', {id: meeting.id}) }}">{{ meeting.meetingName }}</a></th>
                        <td>
                            <a href="{{ path('app_meeting_detail', {id: meeting.id}) }}" class="btn btn-primary">
                                <i class="fas fa-info"></i>
                            </a>
                            <a href="{{ path('app_meeting_delete', {id: meeting.id}) }}" class="btn btn-danger">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/meetings/notfound.html.twig
<h1>404 - Meeting nicht gefunden</h1>
<hr>
Das angeforderte Meeting konnte nicht gefunden werden oder hat noch nicht begonnen.